### ISSUE TITLE
Radiostation Icons

### ISSUE THREAD

**Issue by Nauticno** [LMS-Community/lms-community.github.io#11]
Hi!
When I add a favorit by enter URL address I am not able to upload Icon for the station

![image](https://github.com/LMS-Community/lms-community.github.io/assets/22323906/8dcba9fe-377f-4088-bfc6-0a567fba2c54)

I like to have 

![image](https://github.com/LMS-Community/lms-community.github.io/assets/22323906/36821323-328b-4ad7-94a0-00ec9a40b35b)

Please advise!

**Comment by michaelherger** [comment]
What LMS version are you using? In LMS 8.4 you should be able to define the image when editing a favorite (click the pencil on an entry).

**Comment by Nauticno** [comment]
Hi!
Thank you for quick resoponse! 
I am using "Logitech Media Server Version: 8.4.0 - 1701340594 @ Thu Feb 8 12:26:30 CET 2024"
I am using docker with this image: lmscommunity/logitechmediaserver

Here is my "editing favorite"

![image](https://github.com/LMS-Community/lms-community.github.io/assets/22323906/f1934bd3-9552-48c6-845c-8abe089a4d9c)

I just have Name, Url, Save and Cancel What is wrong?


Best reagards
Nautic

**Comment by Nauticno** [comment]
# docker pull lmscommunity/logitechmediaserver
Using default tag: latest
latest: Pulling from lmscommunity/logitechmediaserver
Digest: sha256:25f9c1899c1c7b5e64f4d2cb8961ff0a5601195060c20ab851c3ae3e2e02c73d
Status: Image is up to date for lmscommunity/logitechmediaserver:latest
docker.io/lmscommunity/logitechmediaserver:latest

**Comment by michaelherger** [comment]
Hmm... that Docker digest doesn't match any of the "latest" image platforms. 

See https://hub.docker.com/r/lmscommunity/logitechmediaserver/tags?page=1&name=latest

Can you please double check you are running the latest and greatest? That change to edit the icons was committed back in December '23.

**Comment by Nauticno** [comment]
Hi!

I changed it to image: lmscommunity/logitechmediaserver:stable then I am able to change icon! Thank you!

Best regards
Nautic
