### ISSUE TITLE
Preferred way to report required changes and corrections to documentation?

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#14]
Process question: how do we want people to report  and request fixes and changes to the documentation - including small typos etc, "rats-and-mice" changes? 

Options would include:

- Raise an Issue like this
- Post into the Forums, for example:- Forums -> Developer Forums -> Developers

**Comment by michaelherger** [comment]
Submit a pull request 😉!

**Comment by Daksol** [comment]
Understood!
