### ISSUE TITLE
Docker build instructions - suggest small improvement

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#23]
In your instructions for building a new Image with the macros module included, it might be useful to mention that there is an essential period character at the end of that line. The period char is there in the notes, but easy to miss!!

`docker build -t squidfunk/mkdocs-material .`

 Good trap for the  unwary otherwise - the error message `ERROR: "docker buildx build" requires exactly 1 argument.` is pretty unhelpful if you leave the period character out.

**Comment by michaelherger** [comment]
Would you mind creating a PR?...

**Comment by Daksol** [comment]
I will do so.
