### ISSUE TITLE
Add pages about software players

### ISSUE THREAD

**Issue by terual** [LMS-Community/lms-community.github.io#25]
In the LMS bundled documentation there are references to JiveLite, Squeezelite and SqueezePlay forum posts (see Help > SoftSqueeze). It would be nice to add pages for those projects to lyrion.org so we can replace the links in the bundled docs to here.

Some questions remain:
- Is this site the best place to maintain information about these projects?
- How do we keep the information about those projects up-to-date? On a forum thread you can update information by posting a new post, which has the upside that it is very easy to keep up-to-date, but has the downside that a new user can't find the latest state of a project easily.

**Comment by ralph-irving** [comment]
> Squeezelite is pretty static, and there's not really a maintainer left, is there? So this could easily go in here.
I assume you meant softsqueeze here?  If so, I did update log4j in softsqueeze to fix the "recent" security issues and I managed to secure admin rights to the softsqueeze sourceforge site after Richard dropped off the radar.
So although I don't develop softsqueeze anymore, it's still useful for developers as it supports the transporter skin for testing code without having to own one.

**Comment by michaelherger** [comment]
I'm sorry, yes, I meant Softsqueeze.

The question was more about where to put user documentation. Would you @ralph-irving have any documentation for the Softsqueeze/Jivelite/Squeezeplay which you'd prefer to have on your hosts rather than here?

**Comment by ralph-irving** [comment]
As for the software players in general, I think we should not rely on forum threads, going forward, if there's a chance of the forums changing when the current hosting contract expires.  And I often forget to update them when new
Let's change the references in documentation once and move forward.
I haven't been following the documentation changes, but feel free to setup the goto references within github and we can archive the threads on the forums.  I'm happy to review any changes and confirm/deny the content.

**Comment by terual** [comment]
Perfect, I will compose some documentation pages and will create PRs so you can review them.

**Comment by ralph-irving** [comment]
For squeezelite, there is the html of the man page at https://ralph-irving.github.io/squeezelite.html which can be moved here as well.  Feel free to grab that version or the original man page format at https://github.com/ralph-irving/squeezelite/raw/master/doc/squeezelite.1 and convert to a format best for the new site.  There might be a few updates to the man page coming shortly once I've had a chance to review some recent PRs for squeezelite. So that might a good opportunity for me to get familiar with the new process.

**Comment by terual** [comment]
I think there are manpage to markdown converters out there, so we can dynamically generate a markdown version from the latest manpage in your repo. I will check if they are good enough to use.

**Comment by terual** [comment]
@ralph-irving The only thing that doesn't convert well is the block with all the  `#define`'s under the Resampling>Flags section of the manpage. This can be solved if in the squeezelite.1 source file that block is surrounded by `.nf–.fi`. Would that consider that change?

**Comment by ralph-irving** [comment]
Yes.  Just post here, or send me a working file and I'll commit it.  Or a PR if that's easier.

**Comment by terual** [comment]
Fixed by #25
