### ISSUE TITLE
Legacy HTML migration: SoftSqueeze /softsqueeze/index.html

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#31]
Legacy HTML Document migration plan

Source:
- Name: Softsqueeze
- Legacy URL: LMSSERVER:LMSPORT/html/docs/softsqueeze/index.html
- HTML file length: 10 lines
- How current: This is now only a series of links to players like squeezelite, not softsqueeze specific. Links point to Forum posts which is probably suboptimal

Migration option:
- Merge this content with other material already in place. Ensure links go to lyrion.org pages, rather than the forums
- Page location: Players & Controllers -> Software Based

Text of existing page
```
SoftSqueeze emulates Squeezebox and Transporter on Windows, Mac OSX and Unix Computers.

Since Server 7.4 SoftSqueeze is replaced by SqueezePlay

Meanwhile SqueezePlay isn't shipped the the standard installation anymore.

There are some Squeeze Software Emulations out there eg. the ones that Ralph Irving maintains.

Name:         Description:                                         Link to our Forum:
Jivelite      Graphical Frontend without Playerfunctionality.     Link
Squeezelite   Commandline Player without Frontend.                Link
SqueezePlay   Graphical Frontend with Playerfunctionality.        Windows
```

**Comment by terual** [comment]
I have already started on some pages for these software players. As soon as they are done we can close this one I think.

**Comment by michaelherger** [comment]
When you start work on an issue, please assign it to you (if you can), and drag it to the "in progress" column in the project.

**Comment by terual** [comment]
Now we have added information to lyrion.org about all mentioned software on this page, I think we can close this issue and remove this page from https://github.com/LMS-Community/slimserver. Do you agree @mherger? Only thing we maybe can add to the pages is a support/troubleshoot section with links to the forums.

**Comment by michaelherger** [comment]
Yes, I've already updated some of them earlier today.

**Comment by terual** [comment]
I was specifically referencing [this link](https://github.com/LMS-Community/slimserver/blob/f58c652527c8fb3a192ac3dd70f7fbdae52a68de/Slim/Web/Pages/Home.pm#L43) and [this page](https://github.com/LMS-Community/slimserver/blob/f58c652527c8fb3a192ac3dd70f7fbdae52a68de/HTML/EN/html/softsqueeze/index.html).

**Comment by terual** [comment]
> I was specifically referencing [this link](https://github.com/LMS-Community/slimserver/blob/f58c652527c8fb3a192ac3dd70f7fbdae52a68de/Slim/Web/Pages/Home.pm#L43) and [this page](https://github.com/LMS-Community/slimserver/blob/f58c652527c8fb3a192ac3dd70f7fbdae52a68de/HTML/EN/html/softsqueeze/index.html).

@mherger: Agree to remove those from slimserver? If yes, I can create a PR

**Comment by michaelherger** [comment]
Oops... sorry, forgot about those. Yes, please. Anything that has moved, incl. the CLI. I might have removed some of the templates, but not any such link in the code.

**Comment by michaelherger** [comment]
Fixed in https://github.com/LMS-Community/slimserver/pull/1050
