### ISSUE TITLE
Legacy-HTML migration: Squeezebox Radio & Logitech Media Server 8+       radio-compatability.html

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#32]
Legacy HTML Document migration plan

Source:
- Name: Squeezebox Radio & Logitech Media Server 8+      
- Legacy URL: LMSSERVER:LMSPORT/html/docs/ radio-compatability.html 
- HTML file length: 12 lines
- How current: looks ok. Info about how certain versions of Firmware for certain Logitech Devices work with different versions of LMS

Migration option:
- Merge this content with other material already in place. 
- Page location: Players & Controllers -> Hardware Based

Text of existing page
```
Squeezebox Radio/Touch/Controller and Logitech Media Server 8+
Unfortunately some firmwares for Squeezebox Radio, Touch, and Controller come with a bug which prevents them from connecting correctly to Logitech Media Server 8+. The version string comparison function fails to recognize 8.0.0 as more recent than 7.7.3. While the bug has been fixed years ago in version 7.8, the fixed firmware never got released to all devices. Unfortunately we're at this point not able to build a fixed firmware for distribution.

But there's a patch available, which you can easily install on an existing Squeezebox Radio/Touch/Controller:

* On the Squeezebox go to Settings/Advanced/Applet Installer, install the Patch Installer. The device will re-boot.

* Once it's back, go to Settings/Advanced/Patch Installer and install the "Version Comparison Fix".

* When done patching all your devices you might need to restart Logitech Media Server to make the warning go away.

Enjoy the music on your Squeezebox Radio/Touch/Controller!


```

**Comment by michaelherger** [comment]
I think we no longer need this. LMS8 has been able to deal with the situation for years.

**Comment by Daksol** [comment]
This content will not be migrated.

Material not migrated can be viewed here:

https://github.com/LMS-Community/slimserver/blob/public/8.5/HTML/EN/html/docs/radio-compatibility.html

https://github.com/LMS-Community/slimserver/blob/public/8.5/HTML/EN/html/docs/radio-compatibility.html.de
