### ISSUE TITLE
Legacy HTML Migration: Skin Creation skins.html

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#34]
Legacy HTML Document migration plan

Source:

Name: Skin Creation

- Legacy URL: LMSSERVER:LMSPORT/html/docs/skins.html
- HTML file length: 604 lines
- How current:  Page starts with line: "**WARNING: This documentation is substantially out of date."**

Migration option:
- Some sort of Graveyard repository?

**Comment by michaelherger** [comment]
Yeah, I see little reason to try to bring this up to date. Today's web technologies would use the approach Material is using: little HTML on the server side, rich JS frontend talking to the backend over an API.

**Comment by Daksol** [comment]
This content will not be migrated.

Material not migrated can be viewed here:

https://github.com/LMS-Community/slimserver/blob/public/8.5/HTML/EN/html/docs/skins.html
