### ISSUE TITLE
Legacy HTML Migration:  The Logitech Media Server xPL Interface xpl.html

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#36]
Source:

Name: The Logitech Media Server xPL Interface   xpl.html
Legacy URL: LMSSERVER:LMSPORT/html/docs/xpl.html
HTML file length: 43 lines
How current: Probably obsolete?
Other info: legacy wiki page https://wiki.slimdevices.com/index.php/XPL.html   
External info: https://xplproject.org.uk/  Not sure if this is the entire project, but last blog post from c. 2016 says that this project is now closed.

Migration option: to be determined

**Comment by michaelherger** [comment]
Legacy, let's drop it.

**Comment by Daksol** [comment]
This content will not be migrated.

Material not migrated can be viewed here:

https://github.com/LMS-Community/slimserver/blob/public/8.5/HTML/EN/html/docs/xpl.html
