### ISSUE TITLE
Legacy HTML Migration: Font Files fonts.html

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#38]
Source:

- Name: Font Files
- Legacy URL: LMSSERVER:LMSPORT/html/docs/fonts.html
- HTML file length: 58 lines
- How current: To be determined

Migration option:

- If current:
     - Page location: Reference -> Development

**Comment by michaelherger** [comment]
Old file: https://github.com/LMS-Community/slimserver/blob/79a893c724015ad4f5871beec711d454f599073d/HTML/EN/html/docs/fonts.html
