### ISSUE TITLE
Lyrion.org Home page - Visibility of second line of headings, and Initial display of LH bar

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/lms-community.github.io#46]
Two point about how the lyrion.org behaves in a browser

### FIRST: The second line of headings only visible when window very wide

I realised that sometimes the lyrion.org home page seemed friendly - with useful links across the top, and other times less so, having to go via the LH sidebar to get anywhere. I now see why it sometimes feels different.

I am viewing on a 1920x1080 HD display.  If the Lyrion.org window is about 1530 pixels or wider you get the two line top bar with link, plus three links in LH sidebar.
The moment the window is narrower than that, that second line disappears- even tho that second line takes fits in a bit less than 900 pixels. And the LH sidebar disappears too. So suddenly there is (almost) nothing left to click!

Could we see if we can tweak the numbers in the CSS Grid control settings to keep the second line visible until window much narrower, certainly leave it there until 900 px wide.

### SECOND First view of LH Sidebar does not include most important links to use

When the LH sidebar is not visible it can be deployed by clicking on the "three horizontal lines" button which appears top left.

The options immediately displayed are _"Home", "Overview" and "Community Forums"._ You have to click on "Home" in order to bring up the (IMHO much more important) links _"Home, Getting started, Players&Controllers, Plugins, Contributing, Reference."_

FOr my money I would rather see the _"links Home, Getting started, Players&Controllers, Plugins, Contributing, Reference."_ set of links straight away, and not have to click twice.

Screenshot shows the lyrion.org in as narrow a window you can have before it removes second line of headings and the LH sidebar.

![image](https://github.com/LMS-Community/lms-community.github.io/assets/42010857/bea3f915-ef37-4ec5-8982-832392d4b559)

**Comment by terual** [comment]
See https://github.com/LMS-Community/lms-community.github.io/tree/fix-responsive-nav for a fix for the second problem (I encountered this also). Consequence is that we need a new place for the link to the forums.

**Comment by terual** [comment]
@Daksol Did you already test the https://github.com/LMS-Community/lms-community.github.io/tree/fix-responsive-nav branch?

**Comment by Daksol** [comment]
> @Daksol Did you already test the https://github.com/LMS-Community/lms-community.github.io/tree/fix-responsive-nav branch?

Hi - thanks for the prompt.

* Got the fix-responsive-nav branch cloned locally
* Looked at how it works on both a mobile, and on a laptop

Looks really good - the most useful options always available.

(I presume the branch was created after the Analytics pages were added, but before an Analytics link wsa created at the top level. Hence no Analytics link shows on top level menus.) 

Thanks

**Comment by terual** [comment]
Any ideas where to put the forums and analytics page link? If we have a new place to put them we can deploy this fix.

**Comment by michaelherger** [comment]
Can the forums link go to the (already quite busy) Getting Started section?

Analytics I'm not even sure need to be linked from one of the menus.

**Comment by michaelherger** [comment]
As for the first issue (please always create to reports for two distinct issues): might be https://github.com/squidfunk/mkdocs-material/discussions/5975, which is considered a bug.

**Comment by terual** [comment]
I have created a draft PR for the issue with the responsive navigation. I have made some choices where to put links, so that is why I created a draft.
