### ISSUE TITLE
Following the download link for logitechmediaserver_8.5.2_amd64.deb results in a 404

### ISSUE THREAD

**Issue by decibyte** [LMS-Community/lms-community.github.io#61]
On [the download page](https://lyrion.org/downloads/), when trying to download [the most recent version of .deb for amd64 Linux](https://downloads.lms-community.org/LogitechMediaServer_v8.5.2/logitechmediaserver_8.5.2_amd64.deb), I run into a 404 page.

**Comment by michaelherger** [comment]
Working fine here. Can you double check with curl or something in verbose mode to see whether it's doing odd forwarding or something?

**Comment by decibyte** [comment]
From my home server, where I want to install it:
```
$ wget https://downloads.lms-community.org/LogitechMediaServer_v8.5.2/logitechmediaserver_8.5.2_amd64.deb
--2024-06-13 13:57:42--  https://downloads.lms-community.org/LogitechMediaServer_v8.5.2/logitechmediaserver_8.5.2_amd64.deb
Resolving downloads.lms-community.org (downloads.lms-community.org)... 172.67.213.99, 104.21.53.138, 2606:4700:3032::6815:358a, ...
Connecting to downloads.lms-community.org (downloads.lms-community.org)|172.67.213.99|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-06-13 13:57:42 ERROR 404: Not Found.
```

From my computer at work, I get the same result. And this page below in my browser. The error message in the browser hints at object permissions. Could it be that it's a private object and you are somehow authorised to access it?

![image](https://github.com/LMS-Community/lms-community.github.io/assets/224219/e77e4f52-58df-4770-ac2d-29342e66e7c0)

**Comment by michaelherger** [comment]
I purged the cache for that file. Maybe that's "fixing" the issue?

**Comment by decibyte** [comment]
Yeah, getting the same results as you. But it also works with wget and in the browser now :) Thanks, Michael!

**Comment by michaelherger** [comment]
Thanks for letting me know! This should not happen. But I'll hopefully remember next time somebody reports a similar issue.
