### ISSUE TITLE
Update CLI documentation with information about how to use JSON over telnet

### ISSUE THREAD

**Issue by michaelherger** [LMS-Community/lms-community.github.io#74]
@sodface Could you please add a few lines to the CLI documentation, too? Explaining how to use the CLI in JSON mode:

https://github.com/LMS-Community/lms-community.github.io/blob/main/docs/reference/cli/introduction.md
https://github.com/LMS-Community/lms-community.github.io/blob/main/docs/reference/cli/using-the-cli.md

_Originally posted by @michaelherger in https://github.com/LMS-Community/slimserver/pull/1146#discussion_r1719340527_

**Comment by sodface** [comment]
I think this can be closed.

**Comment by michaelherger** [comment]
Thanks!
