### ISSUE TITLE
[Proposal] New navigation entry / page

### ISSUE THREAD

**Issue by dnalor** [LMS-Community/lms-community.github.io#81]
There are a number of third party apps for LMS (controllers, Net-UDAP, ...), but currently no place on the site to document them.  
Therefore, I'd propose to change the top-level "Plugins" entry to

Extensions
 - Applications
 - Plugins

and create a page for Applications.

I have a number of these bookmarked, to I could contribute the first version of the page.

**Comment by michaelherger** [comment]
Sounds good to me! Please feel free to submit a PR.
