### ISSUE TITLE
Dead link to official Squeezebox Firmware images

### ISSUE THREAD

**Issue by terual** [LMS-Community/lms-community.github.io#88]
On the downloads page in section Squeezebox Firmware, there is a dead link to http://archive.lms-community.org/update/firmware/8.5.1/

**Comment by michaelherger** [comment]
Thanks! I broke that when I moved the archive from my own web server to the Lyrion downloads bucket. Will look into this ASAP.

**Comment by terual** [comment]
Thanks! No rush, it was just something I came across. I doubt anyone needs this urgently right now.

**Comment by michaelherger** [comment]
I fixed the one link on lyrion.org. But I'll probably have to fix the page handler to cover for other links, too. They might have been posted on the forums etc...
